// <auto-generated />
using System;
using Epros.Modules.Imobiliaria.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Epros.Modules.Imobiliaria.Migrations
{
    [DbContext(typeof(ContextImobiliaria))]
    [Migration("20260802120950_ImobiliariaCicloCompleto")]
    partial class ImobiliariaCicloCompleto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("imobiliaria")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.CobrancaAluguel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("competencia");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DataBaixa")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_baixa");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid>("LocacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("locacao_id");

                    b.Property<string>("ReceberRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("receber_ref");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.Property<decimal>("ValorPago")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_pago");

                    b.Property<int>("Vencimento")
                        .HasColumnType("integer")
                        .HasColumnName("vencimento");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_imo_cobranca_aluguel");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__cobranca_aluguel_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__cobranca_aluguel_tenant_id");

                    b.HasIndex("TenantId", "LocacaoId", "Competencia", "Tipo")
                        .IsUnique()
                        .HasDatabaseName("i_x_imo_cobranca_aluguel_tenant_id_locacao_id_competencia_tipo");

                    b.ToTable("imo_cobranca_aluguel", "imobiliaria");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.ContratoServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("ImovelId")
                        .HasColumnType("uuid")
                        .HasColumnName("imovel_id");

                    b.Property<Guid>("ProprietarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("proprietario_id");

                    b.Property<decimal?>("Remuneracao")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("remuneracao");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("VigenciaFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigencia_fim");

                    b.Property<DateTime?>("VigenciaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigencia_inicio");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_imo_contrato_servico");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__contrato_servico_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__contrato_servico_tenant_id");

                    b.HasIndex("TenantId", "ImovelId")
                        .HasDatabaseName("i_x_imo_contrato_servico_tenant_id_imovel_id");

                    b.HasIndex("TenantId", "ProprietarioId")
                        .HasDatabaseName("i_x_imo_contrato_servico_tenant_id_proprietario_id");

                    b.ToTable("imo_contrato_servico", "imobiliaria");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.Imovel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("cep");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("complemento");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descricao");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("logradouro");

                    b.Property<Guid?>("MunicipioId")
                        .HasColumnType("uuid")
                        .HasColumnName("municipio_id");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Test1")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("test1");

                    b.Property<string>("Test2")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("test2");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_imo_imovel");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__imovel_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__imovel_tenant_id");

                    b.HasIndex("TenantId", "MunicipioId")
                        .HasDatabaseName("i_x_imo_imovel_tenant_id_municipio_id");

                    b.ToTable("imo_imovel", "imobiliaria");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.ImovelCusto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime?>("Competencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("competencia");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uuid")
                        .HasColumnName("imovel_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_imo_imovel_custo");

                    b.HasIndex("ImovelId")
                        .HasDatabaseName("i_x_imo_imovel_custo_imovel_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__imovel_custo_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__imovel_custo_tenant_id");

                    b.HasIndex("TenantId", "ImovelId")
                        .HasDatabaseName("i_x_imo_imovel_custo_tenant_id_imovel_id");

                    b.ToTable("imo_imovel_custo", "imobiliaria");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.ImovelImagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<byte[]>("Conteudo")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uuid")
                        .HasColumnName("imovel_id");

                    b.Property<string>("NomeArquivo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_arquivo");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_imo_imovel_imagem");

                    b.HasIndex("ImovelId")
                        .HasDatabaseName("i_x_imo_imovel_imagem_imovel_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__imovel_imagem_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__imovel_imagem_tenant_id");

                    b.HasIndex("TenantId", "ImovelId")
                        .HasDatabaseName("i_x_imo_imovel_imagem_tenant_id_imovel_id");

                    b.ToTable("imo_imovel_imagem", "imobiliaria");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.ImovelProprietario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uuid")
                        .HasColumnName("imovel_id");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_imo_imovel_proprietario");

                    b.HasIndex("ImovelId")
                        .HasDatabaseName("i_x_imo_imovel_proprietario_imovel_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__imovel_proprietario_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__imovel_proprietario_tenant_id");

                    b.HasIndex("TenantId", "ImovelId", "PessoaId")
                        .IsUnique()
                        .HasDatabaseName("i_x_imo_imovel_proprietario_tenant_id_imovel_id_pessoa_id");

                    b.ToTable("imo_imovel_proprietario", "imobiliaria");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.ImovelVistoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DataVistoria")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vistoria");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uuid")
                        .HasColumnName("imovel_id");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("local");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_imo_imovel_vistoria");

                    b.HasIndex("ImovelId")
                        .HasDatabaseName("i_x_imo_imovel_vistoria_imovel_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__imovel_vistoria_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__imovel_vistoria_tenant_id");

                    b.HasIndex("TenantId", "ImovelId")
                        .HasDatabaseName("i_x_imo_imovel_vistoria_tenant_id_imovel_id");

                    b.ToTable("imo_imovel_vistoria", "imobiliaria");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.Locacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid?>("ImovelId")
                        .HasColumnType("uuid")
                        .HasColumnName("imovel_id");

                    b.Property<DateTime>("PeriodoFinal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("periodo_final");

                    b.Property<DateTime>("PeriodoInicial")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("periodo_inicial");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.Property<int>("Vencimento")
                        .HasColumnType("integer")
                        .HasColumnName("vencimento");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_imo_locacao");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__locacao_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__locacao_tenant_id");

                    b.HasIndex("TenantId", "ImovelId")
                        .HasDatabaseName("i_x_imo_locacao_tenant_id_imovel_id");

                    b.HasIndex("TenantId", "PeriodoInicial", "PeriodoFinal")
                        .HasDatabaseName("i_x_imo_locacao_tenant_id_periodo_inicial_periodo_final");

                    b.ToTable("imo_locacao", "imobiliaria");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.LocacaoCusto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<Guid?>("CustoImovelId")
                        .HasColumnType("uuid")
                        .HasColumnName("custo_imovel_id");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("LocacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("locacao_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_imo_locacao_custo");

                    b.HasIndex("LocacaoId")
                        .HasDatabaseName("i_x_imo_locacao_custo_locacao_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__locacao_custo_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__locacao_custo_tenant_id");

                    b.HasIndex("TenantId", "CustoImovelId")
                        .HasDatabaseName("i_x_imo_locacao_custo_tenant_id_custo_imovel_id");

                    b.HasIndex("TenantId", "LocacaoId")
                        .HasDatabaseName("i_x_imo_locacao_custo_tenant_id_locacao_id");

                    b.ToTable("imo_locacao_custo", "imobiliaria");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.LocacaoDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<byte[]>("Conteudo")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid>("LocacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("locacao_id");

                    b.Property<string>("NomeArquivo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_arquivo");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_imo_locacao_documento");

                    b.HasIndex("LocacaoId")
                        .HasDatabaseName("i_x_imo_locacao_documento_locacao_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__locacao_documento_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__locacao_documento_tenant_id");

                    b.HasIndex("TenantId", "LocacaoId")
                        .HasDatabaseName("i_x_imo_locacao_documento_tenant_id_locacao_id");

                    b.ToTable("imo_locacao_documento", "imobiliaria");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.LocacaoGarantia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("FiadorPessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("fiador_pessoa_id");

                    b.Property<Guid>("LocacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("locacao_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubstituiId")
                        .HasColumnType("uuid")
                        .HasColumnName("substitui_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<decimal>("ValorLimite")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_limite");

                    b.Property<DateTime?>("VigenciaFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigencia_fim");

                    b.Property<DateTime?>("VigenciaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigencia_inicio");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_imo_locacao_garantia");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__locacao_garantia_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__locacao_garantia_tenant_id");

                    b.HasIndex("TenantId", "LocacaoId")
                        .HasDatabaseName("i_x_imo_locacao_garantia_tenant_id_locacao_id");

                    b.HasIndex("TenantId", "SubstituiId")
                        .HasDatabaseName("i_x_imo_locacao_garantia_tenant_id_substitui_id");

                    b.ToTable("imo_locacao_garantia", "imobiliaria");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.LocacaoParte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid>("LocacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("locacao_id");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("papel");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_imo_locacao_parte");

                    b.HasIndex("LocacaoId")
                        .HasDatabaseName("i_x_imo_locacao_parte_locacao_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__locacao_parte_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__locacao_parte_tenant_id");

                    b.HasIndex("TenantId", "LocacaoId", "PessoaId", "Papel")
                        .IsUnique()
                        .HasDatabaseName("i_x_imo_locacao_parte_tenant_id_locacao_id_pessoa_id_papel");

                    b.ToTable("imo_locacao_parte", "imobiliaria");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.LocacaoReajuste", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("DataBase")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_base");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Indice")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("indice");

                    b.Property<Guid>("LocacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("locacao_id");

                    b.Property<decimal?>("PercentualAplicado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("percentual_aplicado");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("ValorAnterior")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_anterior");

                    b.Property<decimal>("ValorNovo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_novo");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_imo_locacao_reajuste");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__locacao_reajuste_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__locacao_reajuste_tenant_id");

                    b.HasIndex("TenantId", "LocacaoId")
                        .HasDatabaseName("i_x_imo_locacao_reajuste_tenant_id_locacao_id");

                    b.ToTable("imo_locacao_reajuste", "imobiliaria");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.LocacaoRescisao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<int?>("AvisoPrevioDias")
                        .HasColumnType("integer")
                        .HasColumnName("aviso_previo_dias");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("DataRescisao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_rescisao");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid>("LocacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("locacao_id");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("motivo");

                    b.Property<decimal>("MultaProporcional")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("multa_proporcional");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("VistoriaSaidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("vistoria_saida_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_imo_locacao_rescisao");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__locacao_rescisao_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__locacao_rescisao_tenant_id");

                    b.HasIndex("TenantId", "LocacaoId")
                        .IsUnique()
                        .HasDatabaseName("i_x_imo_locacao_rescisao_tenant_id_locacao_id");

                    b.ToTable("imo_locacao_rescisao", "imobiliaria");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.Proposta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<Guid?>("ContrapropostaDeId")
                        .HasColumnType("uuid")
                        .HasColumnName("contraproposta_de_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uuid")
                        .HasColumnName("imovel_id");

                    b.Property<Guid?>("LocacaoGeradaId")
                        .HasColumnType("uuid")
                        .HasColumnName("locacao_gerada_id");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observacao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<DateTime>("Validade")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validade");

                    b.Property<decimal>("ValorProposto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_proposto");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_imo_proposta");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__proposta_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__proposta_tenant_id");

                    b.HasIndex("TenantId", "ContrapropostaDeId")
                        .HasDatabaseName("i_x_imo_proposta_tenant_id_contraproposta_de_id");

                    b.HasIndex("TenantId", "ImovelId")
                        .HasDatabaseName("i_x_imo_proposta_tenant_id_imovel_id");

                    b.ToTable("imo_proposta", "imobiliaria");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.PropostaParte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("papel");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<Guid>("PropostaId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposta_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_imo_proposta_parte");

                    b.HasIndex("PropostaId")
                        .HasDatabaseName("i_x_imo_proposta_parte_proposta_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__proposta_parte_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__proposta_parte_tenant_id");

                    b.HasIndex("TenantId", "PropostaId", "PessoaId", "Papel")
                        .IsUnique()
                        .HasDatabaseName("i_x_imo_proposta_parte_tenant_id_proposta_id_pessoa_id_papel");

                    b.ToTable("imo_proposta_parte", "imobiliaria");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.ReciboAluguel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<Guid>("CobrancaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cobranca_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_emissao");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("DocumentoRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("documento_ref");

                    b.Property<Guid>("LocacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("locacao_id");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint")
                        .HasColumnName("numero");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_imo_recibo_aluguel");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__recibo_aluguel_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__recibo_aluguel_tenant_id");

                    b.HasIndex("TenantId", "CobrancaId")
                        .IsUnique()
                        .HasDatabaseName("i_x_imo_recibo_aluguel_tenant_id_cobranca_id");

                    b.HasIndex("TenantId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("i_x_imo_recibo_aluguel_tenant_id_numero");

                    b.ToTable("imo_recibo_aluguel", "imobiliaria");
                });

            modelBuilder.Entity("Epros.Shared.Domain.Events.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Erro")
                        .HasColumnType("text")
                        .HasColumnName("erro");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processado_em");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.HasKey("Id")
                        .HasName("p_k_outbox_messages");

                    b.ToTable("outbox_messages", "imobiliaria");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.ImovelCusto", b =>
                {
                    b.HasOne("Epros.Modules.Imobiliaria.Domain.Entities.Imovel", null)
                        .WithMany("Custos")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_imo_imovel_custo_imo_imovel_imovel_id");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.ImovelImagem", b =>
                {
                    b.HasOne("Epros.Modules.Imobiliaria.Domain.Entities.Imovel", null)
                        .WithMany("Imagens")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_imo_imovel_imagem_imo_imovel_imovel_id");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.ImovelProprietario", b =>
                {
                    b.HasOne("Epros.Modules.Imobiliaria.Domain.Entities.Imovel", null)
                        .WithMany("Proprietarios")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_imo_imovel_proprietario_imo_imovel_imovel_id");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.ImovelVistoria", b =>
                {
                    b.HasOne("Epros.Modules.Imobiliaria.Domain.Entities.Imovel", null)
                        .WithMany("Vistorias")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_imo_imovel_vistoria_imo_imovel_imovel_id");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.LocacaoCusto", b =>
                {
                    b.HasOne("Epros.Modules.Imobiliaria.Domain.Entities.Locacao", null)
                        .WithMany("Custos")
                        .HasForeignKey("LocacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_imo_locacao_custo_imo_locacao_locacao_id");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.LocacaoDocumento", b =>
                {
                    b.HasOne("Epros.Modules.Imobiliaria.Domain.Entities.Locacao", null)
                        .WithMany("Documentos")
                        .HasForeignKey("LocacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_imo_locacao_documento_imo_locacao_locacao_id");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.LocacaoParte", b =>
                {
                    b.HasOne("Epros.Modules.Imobiliaria.Domain.Entities.Locacao", null)
                        .WithMany("Partes")
                        .HasForeignKey("LocacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_imo_locacao_parte_imo_locacao_locacao_id");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.PropostaParte", b =>
                {
                    b.HasOne("Epros.Modules.Imobiliaria.Domain.Entities.Proposta", null)
                        .WithMany("Partes")
                        .HasForeignKey("PropostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_imo_proposta_parte_imo_proposta_proposta_id");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.Imovel", b =>
                {
                    b.Navigation("Custos");

                    b.Navigation("Imagens");

                    b.Navigation("Proprietarios");

                    b.Navigation("Vistorias");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.Locacao", b =>
                {
                    b.Navigation("Custos");

                    b.Navigation("Documentos");

                    b.Navigation("Partes");
                });

            modelBuilder.Entity("Epros.Modules.Imobiliaria.Domain.Entities.Proposta", b =>
                {
                    b.Navigation("Partes");
                });
#pragma warning restore 612, 618
        }
    }
}
