// <auto-generated />
using System;
using Epros.Modules.RH.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Epros.Modules.RH.Migrations
{
    [DbContext(typeof(ContextRH))]
    [Migration("20260627131449_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rh")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Epros.Modules.RH.Domain.Entities.Colaborador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cargo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_admissao");

                    b.Property<DateTime?>("DataDemissao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_demissao");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("departamento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<decimal>("SalarioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("salario_base");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("p_k_colaboradores");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__colaborador_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__colaborador_tenant_id");

                    b.HasIndex("TenantId", "Cpf")
                        .IsUnique()
                        .HasDatabaseName("i_x_colaboradores_tenant_id_cpf");

                    b.ToTable("colaboradores", "rh");
                });

            modelBuilder.Entity("Epros.Modules.RH.Domain.Entities.FolhaPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<int>("AnoCompetencia")
                        .HasColumnType("integer")
                        .HasColumnName("ano_competencia");

                    b.Property<Guid>("ColaboradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("colaborador_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("DataProcessamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_processamento");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<decimal>("Descontos")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("descontos");

                    b.Property<int>("MesCompetencia")
                        .HasColumnType("integer")
                        .HasColumnName("mes_competencia");

                    b.Property<decimal>("SalarioBruto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("salario_bruto");

                    b.Property<decimal>("SalarioLiquido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("salario_liquido");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("p_k_folhas_pagamento");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__folha_pagamento_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__folha_pagamento_tenant_id");

                    b.HasIndex("TenantId", "ColaboradorId", "MesCompetencia", "AnoCompetencia")
                        .IsUnique()
                        .HasDatabaseName("i_x_folhas_pagamento_tenant_id_colaborador_id_mes_competencia_a~");

                    b.ToTable("folhas_pagamento", "rh");
                });

            modelBuilder.Entity("Epros.Modules.RH.Domain.Entities.FolhaPagamentoVerba", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<Guid>("FolhaPagamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("folha_pagamento_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("p_k_folhas_pagamento_verbas");

                    b.HasIndex("FolhaPagamentoId")
                        .HasDatabaseName("i_x_folhas_pagamento_verbas_folha_pagamento_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__folha_pagamento_verba_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__folha_pagamento_verba_tenant_id");

                    b.ToTable("folhas_pagamento_verbas", "rh");
                });

            modelBuilder.Entity("Epros.Modules.RH.Domain.Entities.Timesheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<Guid>("ColaboradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("colaborador_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("DescricaoAtividade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao_atividade");

                    b.Property<decimal>("HorasTrabalhadas")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("horas_trabalhadas");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("p_k_timesheets");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__timesheet_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__timesheet_tenant_id");

                    b.HasIndex("TenantId", "ColaboradorId", "Data")
                        .HasDatabaseName("i_x_timesheets_tenant_id_colaborador_id_data");

                    b.ToTable("timesheets", "rh");
                });

            modelBuilder.Entity("Epros.Shared.Domain.Events.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Erro")
                        .HasColumnType("text")
                        .HasColumnName("erro");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processado_em");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.HasKey("Id")
                        .HasName("p_k_outbox_messages");

                    b.ToTable("outbox_messages", "rh");
                });

            modelBuilder.Entity("Epros.Modules.RH.Domain.Entities.FolhaPagamentoVerba", b =>
                {
                    b.HasOne("Epros.Modules.RH.Domain.Entities.FolhaPagamento", null)
                        .WithMany("Verbas")
                        .HasForeignKey("FolhaPagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_folhas_pagamento_verbas_folhas_pagamento_folha_pagamento_id");
                });

            modelBuilder.Entity("Epros.Modules.RH.Domain.Entities.FolhaPagamento", b =>
                {
                    b.Navigation("Verbas");
                });
#pragma warning restore 612, 618
        }
    }
}
