// <auto-generated />
using System;
using Epros.Modules.Projetos.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Epros.Modules.Projetos.Migrations
{
    [DbContext(typeof(ContextProjetos))]
    [Migration("20260725194110_AddProjetosSubmodulosBackend")]
    partial class AddProjetosSubmodulosBackend
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("projetos")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.AlocacaoRecurso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<Guid>("ColaboradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("colaborador_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<decimal>("CustoHora")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("custo_hora");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("funcao");

                    b.Property<decimal>("HorasPlanejadas")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("horas_planejadas");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uuid")
                        .HasColumnName("projeto_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("p_k_alocacoes");

                    b.HasIndex("ProjetoId")
                        .HasDatabaseName("i_x_alocacoes_projeto_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__alocacao_recurso_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__alocacao_recurso_tenant_id");

                    b.HasIndex("TenantId", "ColaboradorId")
                        .HasDatabaseName("i_x_alocacoes_tenant_id_colaborador_id");

                    b.ToTable("alocacoes", "projetos");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.Definicao.ProjetoArquivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<Guid?>("ArquivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("arquivo_id");

                    b.Property<string>("CaminhoArquivo")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("caminho_arquivo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_arquivo");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uuid")
                        .HasColumnName("projeto_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("p_k_prj_def_projeto_arquivo");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__projeto_arquivo_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__projeto_arquivo_tenant_id");

                    b.HasIndex("TenantId", "ProjetoId")
                        .HasDatabaseName("i_x_prj_def_projeto_arquivo_tenant_id_projeto_id");

                    b.ToTable("prj_def_projeto_arquivo", "projetos");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.Definicao.ProjetoAtividade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observacao");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uuid")
                        .HasColumnName("projeto_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TipoAtividade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_atividade");

                    b.Property<string>("TipoUsuario")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_usuario");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("p_k_prj_def_projeto_atividade");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__projeto_atividade_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__projeto_atividade_tenant_id");

                    b.HasIndex("TenantId", "ProjetoId", "TipoAtividade")
                        .HasDatabaseName("i_x_prj_def_projeto_atividade_tenant_id_projeto_id_tipo_ativida~");

                    b.ToTable("prj_def_projeto_atividade", "projetos");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.Definicao.ProjetoCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uuid")
                        .HasColumnName("projeto_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("p_k_prj_def_projeto_cliente");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__projeto_cliente_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__projeto_cliente_tenant_id");

                    b.HasIndex("TenantId", "ProjetoId", "ClienteId")
                        .HasDatabaseName("i_x_prj_def_projeto_cliente_tenant_id_projeto_id_cliente_id");

                    b.ToTable("prj_def_projeto_cliente", "projetos");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.Definicao.ProjetoMembro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("papel");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uuid")
                        .HasColumnName("projeto_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("p_k_prj_def_projeto_membro");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__projeto_membro_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__projeto_membro_tenant_id");

                    b.HasIndex("TenantId", "ProjetoId", "UsuarioId")
                        .HasDatabaseName("i_x_prj_def_projeto_membro_tenant_id_projeto_id_usuario_id");

                    b.ToTable("prj_def_projeto_membro", "projetos");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.Definicao.ProjetoTarefaModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<decimal>("Duracao")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("duracao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<int>("PercentualCompleto")
                        .HasColumnType("integer")
                        .HasColumnName("percentual_completo");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uuid")
                        .HasColumnName("projeto_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<int?>("TarefaPaiSequencial")
                        .HasColumnType("integer")
                        .HasColumnName("tarefa_pai_sequencial");

                    b.Property<int>("TarefaSequencial")
                        .HasColumnType("integer")
                        .HasColumnName("tarefa_sequencial");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UnidadeDuracao")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unidade_duracao");

                    b.HasKey("Id")
                        .HasName("p_k_prj_def_tarefa_modelo");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__projeto_tarefa_modelo_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__projeto_tarefa_modelo_tenant_id");

                    b.HasIndex("TenantId", "ProjetoId")
                        .HasDatabaseName("i_x_prj_def_tarefa_modelo_tenant_id_projeto_id");

                    b.ToTable("prj_def_tarefa_modelo", "projetos");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.Faturamento.FaturamentoProjeto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vencimento");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("ModalidadeFaturamento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("modalidade_faturamento");

                    b.Property<string>("Moeda")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("moeda");

                    b.Property<string>("MotivoRejeicao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("motivo_rejeicao");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uuid")
                        .HasColumnName("projeto_id");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsavel_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_total");

                    b.Property<int>("Versao")
                        .HasColumnType("integer")
                        .HasColumnName("versao");

                    b.HasKey("Id")
                        .HasName("p_k_prj_faturamento_projeto");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__faturamento_projeto_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__faturamento_projeto_tenant_id");

                    b.HasIndex("TenantId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("i_x_prj_faturamento_projeto_tenant_id_codigo");

                    b.HasIndex("TenantId", "ProjetoId")
                        .HasDatabaseName("i_x_prj_faturamento_projeto_tenant_id_projeto_id");

                    b.ToTable("prj_faturamento_projeto", "projetos");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.Faturamento.ItemFaturamentoProjeto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid>("FaturamentoProjetoId")
                        .HasColumnType("uuid")
                        .HasColumnName("faturamento_projeto_id");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observacao");

                    b.Property<Guid?>("OrigemId")
                        .HasColumnType("uuid")
                        .HasColumnName("origem_id");

                    b.Property<string>("OrigemTipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("origem_tipo");

                    b.Property<decimal?>("Quantidade")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("quantidade");

                    b.Property<int>("Sequencia")
                        .HasColumnType("integer")
                        .HasColumnName("sequencia");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TipoItem")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_item");

                    b.Property<decimal?>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_total");

                    b.Property<decimal?>("ValorUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_unitario");

                    b.HasKey("Id")
                        .HasName("p_k_prj_faturamento_projeto_item");

                    b.HasIndex("FaturamentoProjetoId")
                        .HasDatabaseName("i_x_prj_faturamento_projeto_item_faturamento_projeto_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__item_faturamento_projeto_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__item_faturamento_projeto_tenant_id");

                    b.HasIndex("TenantId", "FaturamentoProjetoId", "Sequencia")
                        .HasDatabaseName("i_x_prj_faturamento_projeto_item_tenant_id_faturamento_projeto_~");

                    b.ToTable("prj_faturamento_projeto_item", "projetos");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.Orcamento.MarcoOrcamentario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<decimal>("Custo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("custo");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid>("OrcamentoProjetoId")
                        .HasColumnType("uuid")
                        .HasColumnName("orcamento_projeto_id");

                    b.Property<int>("Progresso")
                        .HasColumnType("integer")
                        .HasColumnName("progresso");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uuid")
                        .HasColumnName("projeto_id");

                    b.Property<string>("Resumo")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("resumo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("p_k_prj_orcamento_marco");

                    b.HasIndex("OrcamentoProjetoId")
                        .HasDatabaseName("i_x_prj_orcamento_marco_orcamento_projeto_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__marco_orcamentario_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__marco_orcamentario_tenant_id");

                    b.HasIndex("TenantId", "ProjetoId")
                        .HasDatabaseName("i_x_prj_orcamento_marco_tenant_id_projeto_id");

                    b.ToTable("prj_orcamento_marco", "projetos");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.Orcamento.OrcamentoProjeto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<decimal?>("BillingRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("billing_rate");

                    b.Property<string>("BillingType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("billing_type");

                    b.Property<decimal>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("budget");

                    b.Property<decimal?>("CostsEstimate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("costs_estimate");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<decimal?>("EstimatedHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("estimated_hours");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uuid")
                        .HasColumnName("projeto_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Versao")
                        .HasColumnType("integer")
                        .HasColumnName("versao");

                    b.HasKey("Id")
                        .HasName("p_k_prj_orcamento_projeto");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__orcamento_projeto_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__orcamento_projeto_tenant_id");

                    b.HasIndex("TenantId", "ProjetoId")
                        .HasDatabaseName("i_x_prj_orcamento_projeto_tenant_id_projeto_id");

                    b.ToTable("prj_orcamento_projeto", "projetos");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.Projeto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<decimal>("CustoAcumulado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("custo_acumulado");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime?>("DataTermino")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_termino");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<decimal>("OrcamentoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("orcamento_total");

                    b.Property<decimal>("PercentualConclusao")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("percentual_conclusao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("p_k_projetos");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__projeto_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__projeto_tenant_id");

                    b.HasIndex("TenantId", "ClienteId")
                        .HasDatabaseName("i_x_projetos_tenant_id_cliente_id");

                    b.ToTable("projetos", "projetos");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.Rastreamento.DependenciaTarefa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<bool>("Bloqueada")
                        .HasColumnType("boolean")
                        .HasColumnName("bloqueada");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacao");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<Guid>("TarefaDependenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("tarefa_dependente_id");

                    b.Property<Guid>("TarefaPredecessoraId")
                        .HasColumnType("uuid")
                        .HasColumnName("tarefa_predecessora_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TipoDependencia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_dependencia");

                    b.HasKey("Id")
                        .HasName("p_k_prj_rst_dependencia");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__dependencia_tarefa_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__dependencia_tarefa_tenant_id");

                    b.HasIndex("TenantId", "TarefaDependenteId")
                        .HasDatabaseName("i_x_prj_rst_dependencia_tenant_id_tarefa_dependente_id");

                    b.ToTable("prj_rst_dependencia", "projetos");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.Rastreamento.EstagioTarefa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<string>("Cor")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cor");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<bool>("IndicadorConclusao")
                        .HasColumnType("boolean")
                        .HasColumnName("indicador_conclusao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("p_k_prj_rst_estagio");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__estagio_tarefa_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__estagio_tarefa_tenant_id");

                    b.HasIndex("TenantId", "Ordem")
                        .HasDatabaseName("i_x_prj_rst_estagio_tenant_id_ordem");

                    b.ToTable("prj_rst_estagio", "projetos");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.Rastreamento.ReuniaoAcompanhamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Departamento")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("departamento");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fim");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio");

                    b.Property<string>("Local")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("local");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<Guid?>("OrganizadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizador_id");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uuid")
                        .HasColumnName("projeto_id");

                    b.Property<Guid?>("RelatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("relator_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("p_k_prj_rst_reuniao");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__reuniao_acompanhamento_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__reuniao_acompanhamento_tenant_id");

                    b.HasIndex("TenantId", "ProjetoId")
                        .HasDatabaseName("i_x_prj_rst_reuniao_tenant_id_projeto_id");

                    b.ToTable("prj_rst_reuniao", "projetos");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.Rastreamento.SubtarefaChecklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<bool>("Concluido")
                        .HasColumnType("boolean")
                        .HasColumnName("concluido");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DataPrevista")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_prevista");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<Guid?>("ResponsavelId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsavel_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<Guid>("TarefaId")
                        .HasColumnType("uuid")
                        .HasColumnName("tarefa_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("p_k_prj_rst_subtarefa");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__subtarefa_checklist_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__subtarefa_checklist_tenant_id");

                    b.HasIndex("TenantId", "TarefaId")
                        .HasDatabaseName("i_x_prj_rst_subtarefa_tenant_id_tarefa_id");

                    b.ToTable("prj_rst_subtarefa", "projetos");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.Rastreamento.TarefaProjeto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime?>("DataTermino")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_termino");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("descricao");

                    b.Property<decimal?>("Duracao")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("duracao");

                    b.Property<decimal?>("EsforcoEstimado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("esforco_estimado");

                    b.Property<decimal?>("EsforcoRealizado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("esforco_realizado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<Guid?>("EstagioId")
                        .HasColumnType("uuid")
                        .HasColumnName("estagio_id");

                    b.Property<bool>("IndicadorMarco")
                        .HasColumnType("boolean")
                        .HasColumnName("indicador_marco");

                    b.Property<Guid?>("MarcoId")
                        .HasColumnType("uuid")
                        .HasColumnName("marco_id");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<decimal>("PercentualConcluido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("percentual_concluido");

                    b.Property<string>("Prioridade")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("prioridade");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uuid")
                        .HasColumnName("projeto_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<Guid?>("TarefaSuperiorId")
                        .HasColumnType("uuid")
                        .HasColumnName("tarefa_superior_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("titulo");

                    b.Property<string>("Visibilidade")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("visibilidade");

                    b.HasKey("Id")
                        .HasName("p_k_prj_rst_tarefa");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__tarefa_projeto_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__tarefa_projeto_tenant_id");

                    b.HasIndex("TenantId", "ProjetoId", "EstagioId")
                        .HasDatabaseName("i_x_prj_rst_tarefa_tenant_id_projeto_id_estagio_id");

                    b.ToTable("prj_rst_tarefa", "projetos");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.Rastreamento.TimerOperacional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<decimal?>("Duracao")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("duracao");

                    b.Property<DateTime?>("Fim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fim");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacao");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uuid")
                        .HasColumnName("projeto_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<Guid>("TarefaId")
                        .HasColumnType("uuid")
                        .HasColumnName("tarefa_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TipoRegistro")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_registro");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("p_k_prj_rst_timer");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__timer_operacional_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__timer_operacional_tenant_id");

                    b.HasIndex("TenantId", "TarefaId")
                        .HasDatabaseName("i_x_prj_rst_timer_tenant_id_tarefa_id");

                    b.ToTable("prj_rst_timer", "projetos");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.Recursos.RecursoAlocacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<decimal?>("CargaPlanejadaHoras")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("carga_planejada_horas");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("PapelNoProjeto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("papel_no_projeto");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uuid")
                        .HasColumnName("projeto_id");

                    b.Property<Guid>("RecursoId")
                        .HasColumnType("uuid")
                        .HasColumnName("recurso_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<Guid?>("TarefaId")
                        .HasColumnType("uuid")
                        .HasColumnName("tarefa_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("p_k_prj_recurso_alocacao");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__recurso_alocacao_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__recurso_alocacao_tenant_id");

                    b.HasIndex("TenantId", "RecursoId", "ProjetoId")
                        .HasDatabaseName("i_x_prj_recurso_alocacao_tenant_id_recurso_id_projeto_id");

                    b.ToTable("prj_recurso_alocacao", "projetos");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.Recursos.RecursoTimesheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<int>("Horas")
                        .HasColumnType("integer")
                        .HasColumnName("horas");

                    b.Property<int>("Minutos")
                        .HasColumnType("integer")
                        .HasColumnName("minutos");

                    b.Property<string>("Notas")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notas");

                    b.Property<Guid?>("ProjetoId")
                        .HasColumnType("uuid")
                        .HasColumnName("projeto_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<Guid?>("TarefaId")
                        .HasColumnType("uuid")
                        .HasColumnName("tarefa_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<int>("Versao")
                        .HasColumnType("integer")
                        .HasColumnName("versao");

                    b.HasKey("Id")
                        .HasName("p_k_prj_recurso_timesheet");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__recurso_timesheet_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__recurso_timesheet_tenant_id");

                    b.HasIndex("TenantId", "ProjetoId", "TarefaId")
                        .HasDatabaseName("i_x_prj_recurso_timesheet_tenant_id_projeto_id_tarefa_id");

                    b.HasIndex("TenantId", "UsuarioId", "Data")
                        .HasDatabaseName("i_x_prj_recurso_timesheet_tenant_id_usuario_id_data");

                    b.ToTable("prj_recurso_timesheet", "projetos");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.WbsItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime>("DataTermino")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_termino");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PercentualConclusao")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("percentual_conclusao");

                    b.Property<decimal>("PesoPonderado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("peso_ponderado");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uuid")
                        .HasColumnName("projeto_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("p_k_wbs_itens");

                    b.HasIndex("ProjetoId")
                        .HasDatabaseName("i_x_wbs_itens_projeto_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__wbs_item_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__wbs_item_tenant_id");

                    b.ToTable("wbs_itens", "projetos");
                });

            modelBuilder.Entity("Epros.Shared.Domain.Events.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Erro")
                        .HasColumnType("text")
                        .HasColumnName("erro");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processado_em");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.HasKey("Id")
                        .HasName("p_k_outbox_messages");

                    b.ToTable("outbox_messages", "projetos");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.AlocacaoRecurso", b =>
                {
                    b.HasOne("Epros.Modules.Projetos.Domain.Entities.Projeto", null)
                        .WithMany("Alocacoes")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_alocacoes_projetos_projeto_id");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.Faturamento.ItemFaturamentoProjeto", b =>
                {
                    b.HasOne("Epros.Modules.Projetos.Domain.Entities.Faturamento.FaturamentoProjeto", null)
                        .WithMany("Itens")
                        .HasForeignKey("FaturamentoProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_prj_faturamento_projeto_item_prj_faturamento_projeto_fatura~");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.Orcamento.MarcoOrcamentario", b =>
                {
                    b.HasOne("Epros.Modules.Projetos.Domain.Entities.Orcamento.OrcamentoProjeto", null)
                        .WithMany("Marcos")
                        .HasForeignKey("OrcamentoProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_prj_orcamento_marco_prj_orcamento_projeto_orcamento_projeto~");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.WbsItem", b =>
                {
                    b.HasOne("Epros.Modules.Projetos.Domain.Entities.Projeto", null)
                        .WithMany("ItensWbs")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_wbs_itens_projetos_projeto_id");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.Faturamento.FaturamentoProjeto", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.Orcamento.OrcamentoProjeto", b =>
                {
                    b.Navigation("Marcos");
                });

            modelBuilder.Entity("Epros.Modules.Projetos.Domain.Entities.Projeto", b =>
                {
                    b.Navigation("Alocacoes");

                    b.Navigation("ItensWbs");
                });
#pragma warning restore 612, 618
        }
    }
}
