// <auto-generated />
using System;
using Epros.Modules.Financeiro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Epros.Modules.Financeiro.Migrations
{
    [DbContext(typeof(ContextFinanceiro))]
    [Migration("20260605225807_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("financas")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Epros.Modules.Financeiro.Domain.Entities.ContaPagar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pagamento");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vencimento");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("fornecedor_id");

                    b.Property<string>("Historico")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("historico");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_documento");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("p_k_contas_pagar");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__conta_pagar_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__conta_pagar_tenant_id");

                    b.HasIndex("TenantId", "DataVencimento")
                        .HasDatabaseName("ix_contas_pagar_tenant_vencimento");

                    b.HasIndex("TenantId", "FornecedorId")
                        .HasDatabaseName("ix_contas_pagar_tenant_fornecedor");

                    b.ToTable("contas_pagar", "financas");
                });

            modelBuilder.Entity("Epros.Modules.Financeiro.Domain.Entities.ContaPagarBaixa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<Guid>("ContaPagarId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_pagar_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pagamento");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("forma_pagamento");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("ValorPago")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_pago");

                    b.HasKey("Id")
                        .HasName("p_k_contas_pagar_baixas");

                    b.HasIndex("ContaPagarId")
                        .HasDatabaseName("i_x_contas_pagar_baixas_conta_pagar_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__conta_pagar_baixa_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__conta_pagar_baixa_tenant_id");

                    b.ToTable("contas_pagar_baixas", "financas");
                });

            modelBuilder.Entity("Epros.Modules.Financeiro.Domain.Entities.ContaReceber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DataRecebimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_recebimento");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vencimento");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("DocumentoOrigemId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_origem_id");

                    b.Property<string>("Historico")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("historico");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_documento");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("origem");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("p_k_contas_receber");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__conta_receber_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__conta_receber_tenant_id");

                    b.HasIndex("TenantId", "ClienteId")
                        .HasDatabaseName("ix_contas_receber_tenant_cliente");

                    b.HasIndex("TenantId", "DataVencimento")
                        .HasDatabaseName("ix_contas_receber_tenant_vencimento");

                    b.ToTable("contas_receber", "financas");
                });

            modelBuilder.Entity("Epros.Modules.Financeiro.Domain.Entities.ContaReceberBaixa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<Guid>("ContaReceberId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_receber_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("DataRecebimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_recebimento");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("forma_pagamento");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("ValorRecebido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_recebido");

                    b.HasKey("Id")
                        .HasName("p_k_contas_receber_baixas");

                    b.HasIndex("ContaReceberId")
                        .HasDatabaseName("i_x_contas_receber_baixas_conta_receber_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__conta_receber_baixa_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__conta_receber_baixa_tenant_id");

                    b.ToTable("contas_receber_baixas", "financas");
                });

            modelBuilder.Entity("Epros.Modules.Financeiro.Infrastructure.Data.PessoaJuridicaLookup", b =>
                {
                    b.Property<Guid>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cnpj");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razao_social");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("PessoaId")
                        .HasName("p_k_pessoas_juridicas");

                    b.ToTable("pessoas_juridicas", "plataforma");
                });

            modelBuilder.Entity("Epros.Modules.Financeiro.Infrastructure.Data.PessoaLookup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<bool>("EhFornecedor")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_fornecedor");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_pessoa");

                    b.HasKey("Id")
                        .HasName("p_k_pessoas");

                    b.ToTable("pessoas", "plataforma");
                });

            modelBuilder.Entity("Epros.Shared.Domain.Events.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Erro")
                        .HasColumnType("text")
                        .HasColumnName("erro");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processado_em");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.HasKey("Id")
                        .HasName("p_k_outbox_messages");

                    b.ToTable("outbox_messages", "estoque");
                });

            modelBuilder.Entity("Epros.Modules.Financeiro.Domain.Entities.ContaPagarBaixa", b =>
                {
                    b.HasOne("Epros.Modules.Financeiro.Domain.Entities.ContaPagar", null)
                        .WithMany("Baixas")
                        .HasForeignKey("ContaPagarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_contas_pagar_baixas_contas_pagar_conta_pagar_id");
                });

            modelBuilder.Entity("Epros.Modules.Financeiro.Domain.Entities.ContaReceberBaixa", b =>
                {
                    b.HasOne("Epros.Modules.Financeiro.Domain.Entities.ContaReceber", null)
                        .WithMany("Baixas")
                        .HasForeignKey("ContaReceberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_contas_receber_baixas_contas_receber_conta_receber_id");
                });

            modelBuilder.Entity("Epros.Modules.Financeiro.Domain.Entities.ContaPagar", b =>
                {
                    b.Navigation("Baixas");
                });

            modelBuilder.Entity("Epros.Modules.Financeiro.Domain.Entities.ContaReceber", b =>
                {
                    b.Navigation("Baixas");
                });
#pragma warning restore 612, 618
        }
    }
}
