// <auto-generated />
using System;
using Epros.Modules.Agricultor.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Epros.Modules.Agricultor.Migrations
{
    [DbContext(typeof(ContextAgricultor))]
    [Migration("20260802213947_AddEnderecoLcdprImovel_0040")]
    partial class AddEnderecoLcdprImovel_0040
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("agricultor")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.AnotacaoCampo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("DesignadoA")
                        .HasColumnType("uuid")
                        .HasColumnName("designado_a");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("LatLng")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("lat_lng");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<Guid?>("TalhaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("talhao_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_agr_anotacao_campo");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__anotacao_campo_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__anotacao_campo_tenant_id");

                    b.HasIndex("TenantId", "TalhaoId")
                        .HasDatabaseName("i_x_agr_anotacao_campo_tenant_id_talhao_id");

                    b.ToTable("agr_anotacao_campo", "agricultor");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.CategoriaDespesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<string>("Codigo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<bool>("EhFolhaMaoDeObra")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_folha_mao_de_obra");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_agr_categoria_despesa");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__categoria_despesa_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__categoria_despesa_tenant_id");

                    b.HasIndex("TenantId", "Nome")
                        .HasDatabaseName("i_x_agr_categoria_despesa_tenant_id_nome");

                    b.ToTable("agr_categoria_despesa", "agricultor");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.Colaborador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("papel");

                    b.Property<Guid>("PropriedadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("propriedade_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_agr_colaborador");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__colaborador_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__colaborador_tenant_id");

                    b.HasIndex("TenantId", "PropriedadeId")
                        .HasDatabaseName("i_x_agr_colaborador_tenant_id_propriedade_id");

                    b.ToTable("agr_colaborador", "agricultor");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.Cultura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<string>("Codigo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_agr_cultura");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__cultura_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__cultura_tenant_id");

                    b.HasIndex("TenantId", "Nome")
                        .HasDatabaseName("i_x_agr_cultura_tenant_id_nome");

                    b.ToTable("agr_cultura", "agricultor");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.Despesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<int?>("CodContaLcdpr")
                        .HasColumnType("integer")
                        .HasColumnName("cod_conta_lcdpr");

                    b.Property<int?>("CodImovelLcdpr")
                        .HasColumnType("integer")
                        .HasColumnName("cod_imovel_lcdpr");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid?>("FornecedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("fornecedor_id");

                    b.Property<string>("IdParticLcdpr")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("id_partic_lcdpr");

                    b.Property<Guid>("PropriedadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("propriedade_id");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("referencia");

                    b.Property<Guid?>("SafraId")
                        .HasColumnType("uuid")
                        .HasColumnName("safra_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<Guid?>("TalhaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("talhao_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TipoDocLcdpr")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_doc_lcdpr");

                    b.Property<string>("TipoLancLcdpr")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_lanc_lcdpr");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_agr_despesa");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__despesa_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__despesa_tenant_id");

                    b.HasIndex("TenantId", "PropriedadeId")
                        .HasDatabaseName("i_x_agr_despesa_tenant_id_propriedade_id");

                    b.HasIndex("TenantId", "SafraId")
                        .HasDatabaseName("i_x_agr_despesa_tenant_id_safra_id");

                    b.ToTable("agr_despesa", "agricultor");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<string>("Codigo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<string>("CpfCnpj")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf_cnpj");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_agr_fornecedor");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__fornecedor_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__fornecedor_tenant_id");

                    b.HasIndex("TenantId", "Nome")
                        .HasDatabaseName("i_x_agr_fornecedor_tenant_id_nome");

                    b.ToTable("agr_fornecedor", "agricultor");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.LcdprConta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Agencia")
                        .HasColumnType("integer")
                        .HasColumnName("agencia");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<int?>("Banco")
                        .HasColumnType("integer")
                        .HasColumnName("banco");

                    b.Property<int>("CodConta")
                        .HasColumnType("integer")
                        .HasColumnName("cod_conta");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid>("EscrituracaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("escrituracao_id");

                    b.Property<string>("NumConta")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("num_conta");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_lcdpr_conta");

                    b.HasIndex("EscrituracaoId")
                        .HasDatabaseName("i_x_lcdpr_conta_escrituracao_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__lcdpr_conta_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__lcdpr_conta_tenant_id");

                    b.HasIndex("TenantId", "EscrituracaoId", "CodConta")
                        .IsUnique()
                        .HasDatabaseName("i_x_lcdpr_conta_tenant_id_escrituracao_id_cod_conta");

                    b.ToTable("lcdpr_conta", "agricultor");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.LcdprDadosCadastrais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<string>("Cep")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("cep");

                    b.Property<string>("CodMunicipio")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("cod_municipio");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("endereco");

                    b.Property<Guid>("EscrituracaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("escrituracao_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_lcdpr_dados_cadastrais");

                    b.HasIndex("EscrituracaoId")
                        .IsUnique()
                        .HasDatabaseName("i_x_lcdpr_dados_cadastrais_escrituracao_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__lcdpr_dados_cadastrais_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__lcdpr_dados_cadastrais_tenant_id");

                    b.HasIndex("TenantId", "EscrituracaoId")
                        .IsUnique()
                        .HasDatabaseName("i_x_lcdpr_dados_cadastrais_tenant_id_escrituracao_id");

                    b.ToTable("lcdpr_dados_cadastrais", "agricultor");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.LcdprEscrituracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<DateTime>("DtFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_fin");

                    b.Property<DateTime>("DtIni")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_ini");

                    b.Property<string>("FormaApuracao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("forma_apuracao");

                    b.Property<string>("IdentificacaoCpfCnpj")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("identificacao_cpf_cnpj");

                    b.Property<string>("IdentificacaoNome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("identificacao_nome");

                    b.Property<int>("IndSituacaoInicioPeriodo")
                        .HasColumnType("integer")
                        .HasColumnName("ind_situacao_inicio_periodo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int>("SituacaoEspecial")
                        .HasColumnType("integer")
                        .HasColumnName("situacao_especial");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_lcdpr_escrituracao");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__lcdpr_escrituracao_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__lcdpr_escrituracao_tenant_id");

                    b.HasIndex("TenantId", "Cpf", "DtFin")
                        .IsUnique()
                        .HasDatabaseName("i_x_lcdpr_escrituracao_tenant_id_cpf_dt_fin");

                    b.ToTable("lcdpr_escrituracao", "agricultor");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.LcdprImovel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<string>("Bairro")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("bairro");

                    b.Property<string>("CadItrCafir")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cad_itr_cafir");

                    b.Property<string>("Caepf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("caepf");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cep");

                    b.Property<int>("CodImovel")
                        .HasColumnType("integer")
                        .HasColumnName("cod_imovel");

                    b.Property<string>("CodMunicipio")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("cod_municipio");

                    b.Property<string>("Compl")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("compl");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Endereco")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("endereco");

                    b.Property<Guid>("EscrituracaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("escrituracao_id");

                    b.Property<string>("NomeImovel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_imovel");

                    b.Property<string>("Num")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("num");

                    b.Property<decimal>("Participacao")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("participacao");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TipoExploracao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo_exploracao");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_lcdpr_imovel");

                    b.HasIndex("EscrituracaoId")
                        .HasDatabaseName("i_x_lcdpr_imovel_escrituracao_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__lcdpr_imovel_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__lcdpr_imovel_tenant_id");

                    b.HasIndex("TenantId", "EscrituracaoId", "CodImovel")
                        .IsUnique()
                        .HasDatabaseName("i_x_lcdpr_imovel_tenant_id_escrituracao_id_cod_imovel");

                    b.ToTable("lcdpr_imovel", "agricultor");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.LcdprLancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<int>("CodConta")
                        .HasColumnType("integer")
                        .HasColumnName("cod_conta");

                    b.Property<int>("CodImovel")
                        .HasColumnType("integer")
                        .HasColumnName("cod_imovel");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid>("EscrituracaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("escrituracao_id");

                    b.Property<string>("Historico")
                        .HasColumnType("text")
                        .HasColumnName("historico");

                    b.Property<string>("IdPartic")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("id_partic");

                    b.Property<string>("NumDoc")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("num_doc");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TipoDoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_doc");

                    b.Property<string>("TipoLanc")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_lanc");

                    b.Property<decimal>("VlEntrada")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("vl_entrada");

                    b.Property<decimal>("VlSaida")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("vl_saida");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_lcdpr_lancamento");

                    b.HasIndex("EscrituracaoId")
                        .HasDatabaseName("i_x_lcdpr_lancamento_escrituracao_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__lcdpr_lancamento_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__lcdpr_lancamento_tenant_id");

                    b.HasIndex("TenantId", "EscrituracaoId", "Data")
                        .HasDatabaseName("i_x_lcdpr_lancamento_tenant_id_escrituracao_id_data");

                    b.ToTable("lcdpr_lancamento", "agricultor");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.LcdprParamObrigatoriedade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<decimal>("LimiteValor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("limite_valor");

                    b.Property<string>("Origem")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("origem");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_lcdpr_param_obrigatoriedade");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__lcdpr_param_obrigatoriedade_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__lcdpr_param_obrigatoriedade_tenant_id");

                    b.HasIndex("TenantId", "Ano")
                        .IsUnique()
                        .HasDatabaseName("i_x_lcdpr_param_obrigatoriedade_tenant_id_ano");

                    b.ToTable("lcdpr_param_obrigatoriedade", "agricultor");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.LcdprTerceiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<int>("CodImovel")
                        .HasColumnType("integer")
                        .HasColumnName("cod_imovel");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("IdContraparte")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("id_contraparte");

                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uuid")
                        .HasColumnName("imovel_id");

                    b.Property<string>("NomeContraparte")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_contraparte");

                    b.Property<decimal>("PercContraparte")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("perc_contraparte");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TipoContraparte")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_contraparte");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_lcdpr_terceiro");

                    b.HasIndex("ImovelId")
                        .HasDatabaseName("i_x_lcdpr_terceiro_imovel_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__lcdpr_terceiro_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__lcdpr_terceiro_tenant_id");

                    b.HasIndex("TenantId", "ImovelId")
                        .HasDatabaseName("i_x_lcdpr_terceiro_tenant_id_imovel_id");

                    b.ToTable("lcdpr_terceiro", "agricultor");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.PropriedadeRural", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<decimal>("AreaTotalM2")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("area_total_m2");

                    b.Property<string>("CadItrCafir")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cad_itr_cafir");

                    b.Property<string>("Caepf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("caepf");

                    b.Property<string>("Car")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("car");

                    b.Property<string>("Cep")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("cep");

                    b.Property<string>("CodigoMunicipioSped")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("codigo_municipio_sped");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Endereco")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("endereco");

                    b.Property<string>("Matricula")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("matricula");

                    b.Property<string>("NomeImovel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_imovel");

                    b.Property<decimal>("Participacao")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("participacao");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TipoExploracao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo_exploracao");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_agr_propriedade_rural");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__propriedade_rural_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__propriedade_rural_tenant_id");

                    b.HasIndex("TenantId", "NomeImovel")
                        .HasDatabaseName("i_x_agr_propriedade_rural_tenant_id_nome_imovel");

                    b.ToTable("agr_propriedade_rural", "agricultor");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.ReceitaProducao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<int?>("CodContaLcdpr")
                        .HasColumnType("integer")
                        .HasColumnName("cod_conta_lcdpr");

                    b.Property<int?>("CodImovelLcdpr")
                        .HasColumnType("integer")
                        .HasColumnName("cod_imovel_lcdpr");

                    b.Property<string>("Comprador")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("comprador");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("IdParticLcdpr")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("id_partic_lcdpr");

                    b.Property<string>("NumNf")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("num_nf");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("preco");

                    b.Property<Guid>("PropriedadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("propriedade_id");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("quantidade");

                    b.Property<Guid?>("SafraId")
                        .HasColumnType("uuid")
                        .HasColumnName("safra_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<Guid?>("TalhaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("talhao_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_agr_receita_producao");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__receita_producao_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__receita_producao_tenant_id");

                    b.HasIndex("TenantId", "PropriedadeId")
                        .HasDatabaseName("i_x_agr_receita_producao_tenant_id_propriedade_id");

                    b.HasIndex("TenantId", "SafraId")
                        .HasDatabaseName("i_x_agr_receita_producao_tenant_id_safra_id");

                    b.ToTable("agr_receita_producao", "agricultor");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.Safra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<Guid>("CulturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cultura_id");

                    b.Property<DateTime?>("DataColheita")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_colheita");

                    b.Property<DateTime?>("DataPlantio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_plantio");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<Guid>("TalhaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("talhao_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_agr_safra");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__safra_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__safra_tenant_id");

                    b.HasIndex("TenantId", "CulturaId")
                        .HasDatabaseName("i_x_agr_safra_tenant_id_cultura_id");

                    b.HasIndex("TenantId", "TalhaoId")
                        .HasDatabaseName("i_x_agr_safra_tenant_id_talhao_id");

                    b.ToTable("agr_safra", "agricultor");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.Talhao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<decimal>("AreaM2")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("area_m2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<Guid?>("CulturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cultura_id");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("PoligonoGeoJson")
                        .HasColumnType("text")
                        .HasColumnName("poligono_geo_json");

                    b.Property<Guid>("PropriedadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("propriedade_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("p_k_agr_talhao");

                    b.HasIndex("PropriedadeId")
                        .HasDatabaseName("i_x_agr_talhao_propriedade_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__talhao_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__talhao_tenant_id");

                    b.HasIndex("TenantId", "PropriedadeId")
                        .HasDatabaseName("i_x_agr_talhao_tenant_id_propriedade_id");

                    b.ToTable("agr_talhao", "agricultor");
                });

            modelBuilder.Entity("Epros.Shared.Domain.Events.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Erro")
                        .HasColumnType("text")
                        .HasColumnName("erro");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processado_em");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.HasKey("Id")
                        .HasName("p_k_outbox_messages");

                    b.ToTable("outbox_messages", "agricultor");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.LcdprConta", b =>
                {
                    b.HasOne("Epros.Modules.Agricultor.Domain.Entities.LcdprEscrituracao", null)
                        .WithMany("Contas")
                        .HasForeignKey("EscrituracaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_lcdpr_conta_lcdpr_escrituracao_escrituracao_id");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.LcdprDadosCadastrais", b =>
                {
                    b.HasOne("Epros.Modules.Agricultor.Domain.Entities.LcdprEscrituracao", null)
                        .WithOne("DadosCadastrais")
                        .HasForeignKey("Epros.Modules.Agricultor.Domain.Entities.LcdprDadosCadastrais", "EscrituracaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_lcdpr_dados_cadastrais_lcdpr_escrituracao_escrituracao_id");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.LcdprImovel", b =>
                {
                    b.HasOne("Epros.Modules.Agricultor.Domain.Entities.LcdprEscrituracao", null)
                        .WithMany("Imoveis")
                        .HasForeignKey("EscrituracaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_lcdpr_imovel_lcdpr_escrituracao_escrituracao_id");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.LcdprLancamento", b =>
                {
                    b.HasOne("Epros.Modules.Agricultor.Domain.Entities.LcdprEscrituracao", null)
                        .WithMany("Lancamentos")
                        .HasForeignKey("EscrituracaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_lcdpr_lancamento_lcdpr_escrituracao_escrituracao_id");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.LcdprTerceiro", b =>
                {
                    b.HasOne("Epros.Modules.Agricultor.Domain.Entities.LcdprImovel", null)
                        .WithMany("Terceiros")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_lcdpr_terceiro_lcdpr_imovel_imovel_id");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.Talhao", b =>
                {
                    b.HasOne("Epros.Modules.Agricultor.Domain.Entities.PropriedadeRural", null)
                        .WithMany("Talhoes")
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_agr_talhao_agr_propriedade_rural_propriedade_id");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.LcdprEscrituracao", b =>
                {
                    b.Navigation("Contas");

                    b.Navigation("DadosCadastrais");

                    b.Navigation("Imoveis");

                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.LcdprImovel", b =>
                {
                    b.Navigation("Terceiros");
                });

            modelBuilder.Entity("Epros.Modules.Agricultor.Domain.Entities.PropriedadeRural", b =>
                {
                    b.Navigation("Talhoes");
                });
#pragma warning restore 612, 618
        }
    }
}
