// <auto-generated />
using System;
using Epros.Modules.Producao.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Epros.Modules.Producao.Migrations
{
    [DbContext(typeof(ContextProducao))]
    [Migration("20260627123503_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("producao")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Epros.Modules.Producao.Domain.Entities.ApontamentoProducao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Operador")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operador");

                    b.Property<Guid>("OrdemProducaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ordem_producao_id");

                    b.Property<decimal>("QuantidadeApontada")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("quantidade_apontada");

                    b.Property<decimal>("QuantidadeRefugada")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("quantidade_refugada");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("p_k_apontamentos");

                    b.HasIndex("OrdemProducaoId")
                        .HasDatabaseName("i_x_apontamentos_ordem_producao_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__apontamento_producao_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__apontamento_producao_tenant_id");

                    b.HasIndex("TenantId", "OrdemProducaoId")
                        .HasDatabaseName("i_x_apontamentos_tenant_id_ordem_producao_id");

                    b.ToTable("apontamentos", "producao");
                });

            modelBuilder.Entity("Epros.Modules.Producao.Domain.Entities.BomItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("InsumoSku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("insumo_sku");

                    b.Property<Guid>("ListaMateriaisId")
                        .HasColumnType("uuid")
                        .HasColumnName("lista_materiais_id");

                    b.Property<decimal>("QuantidadeNecessaria")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("quantidade_necessaria");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unidade_medida");

                    b.HasKey("Id")
                        .HasName("p_k_bom_itens");

                    b.HasIndex("ListaMateriaisId")
                        .HasDatabaseName("i_x_bom_itens_lista_materiais_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__bom_item_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__bom_item_tenant_id");

                    b.HasIndex("TenantId", "InsumoSku")
                        .HasDatabaseName("i_x_bom_itens_tenant_id_insumo_sku");

                    b.ToTable("bom_itens", "producao");
                });

            modelBuilder.Entity("Epros.Modules.Producao.Domain.Entities.ListaMateriais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("ProdutoAcabadoSku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("produto_acabado_sku");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("versao");

                    b.HasKey("Id")
                        .HasName("p_k_listas_materiais");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__lista_materiais_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__lista_materiais_tenant_id");

                    b.HasIndex("TenantId", "ProdutoAcabadoSku")
                        .HasDatabaseName("i_x_listas_materiais_tenant_id_produto_acabado_sku");

                    b.ToTable("listas_materiais", "producao");
                });

            modelBuilder.Entity("Epros.Modules.Producao.Domain.Entities.OrdemProducao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<decimal>("CustoTotalProducao")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("custo_total_producao");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_abertura");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("ProdutoAcabadoSku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("produto_acabado_sku");

                    b.Property<decimal>("QuantidadePlanejada")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("quantidade_planejada");

                    b.Property<decimal>("QuantidadeProduzida")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("quantidade_produzida");

                    b.Property<decimal>("QuantidadeRefugada")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("quantidade_refugada");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("p_k_ordens_producao");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__ordem_producao_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__ordem_producao_tenant_id");

                    b.HasIndex("TenantId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("i_x_ordens_producao_tenant_id_codigo");

                    b.HasIndex("TenantId", "ProdutoAcabadoSku")
                        .HasDatabaseName("i_x_ordens_producao_tenant_id_produto_acabado_sku");

                    b.ToTable("ordens_producao", "producao");
                });

            modelBuilder.Entity("Epros.Shared.Domain.Events.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Erro")
                        .HasColumnType("text")
                        .HasColumnName("erro");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processado_em");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.HasKey("Id")
                        .HasName("p_k_outbox_messages");

                    b.ToTable("outbox_messages", "producao");
                });

            modelBuilder.Entity("Epros.Modules.Producao.Domain.Entities.ApontamentoProducao", b =>
                {
                    b.HasOne("Epros.Modules.Producao.Domain.Entities.OrdemProducao", null)
                        .WithMany("Apontamentos")
                        .HasForeignKey("OrdemProducaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_apontamentos_ordens_producao_ordem_producao_id");
                });

            modelBuilder.Entity("Epros.Modules.Producao.Domain.Entities.BomItem", b =>
                {
                    b.HasOne("Epros.Modules.Producao.Domain.Entities.ListaMateriais", null)
                        .WithMany("Itens")
                        .HasForeignKey("ListaMateriaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_bom_itens_listas_materiais_lista_materiais_id");
                });

            modelBuilder.Entity("Epros.Modules.Producao.Domain.Entities.ListaMateriais", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Epros.Modules.Producao.Domain.Entities.OrdemProducao", b =>
                {
                    b.Navigation("Apontamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
