// <auto-generated />
using System;
using Epros.Modules.GestaoClientes.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Epros.Modules.GestaoClientes.Migrations
{
    [DbContext(typeof(ContextGestaoClientes))]
    [Migration("20260605231028_EnableRlsOnExistingTables")]
    partial class EnableRlsOnExistingTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("plataforma")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cnpj");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("PlanoId")
                        .HasColumnType("uuid")
                        .HasColumnName("plano_id");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razao_social");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("p_k_clientes");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__cliente_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__cliente_tenant_id");

                    b.ToTable("clientes", "plataforma");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("integer")
                        .HasColumnName("dia_vencimento");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UltimoFaturamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_faturamento");

                    b.Property<decimal>("ValorRecorrente")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_recorrente");

                    b.HasKey("Id")
                        .HasName("p_k_contratos");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__contrato_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__contrato_tenant_id");

                    b.ToTable("contratos", "plataforma");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.ContratoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_unitario");

                    b.HasKey("Id")
                        .HasName("p_k_contrato_itens");

                    b.HasIndex("ContratoId")
                        .HasDatabaseName("i_x_contrato_itens_contrato_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__contrato_item_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__contrato_item_tenant_id");

                    b.ToTable("contrato_itens", "plataforma");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid?>("CertificadoDigitalId")
                        .HasColumnType("uuid")
                        .HasColumnName("certificado_digital_id");

                    b.Property<string>("Cnae")
                        .HasColumnType("text")
                        .HasColumnName("cnae");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cnpj");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid?>("EmpresaParametrosDfeId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_parametros_dfe_id");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("text")
                        .HasColumnName("inscricao_estadual");

                    b.Property<string>("InscricaoMunicipal")
                        .HasColumnType("text")
                        .HasColumnName("inscricao_municipal");

                    b.Property<string>("InscricaoSuframa")
                        .HasColumnType("text")
                        .HasColumnName("inscricao_suframa");

                    b.Property<string>("LinkWebApiAppVendas")
                        .HasColumnType("text")
                        .HasColumnName("link_web_api_app_vendas");

                    b.Property<string>("Logo")
                        .HasColumnType("text")
                        .HasColumnName("logo");

                    b.Property<Guid?>("NcmTributacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ncm_tributacao_id");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("text")
                        .HasColumnName("nome_fantasia");

                    b.Property<Guid?>("PessoaGrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_grupo_id");

                    b.Property<Guid?>("PlanoContasFinanceiroId")
                        .HasColumnType("uuid")
                        .HasColumnName("plano_contas_financeiro_id");

                    b.Property<Guid?>("ProdutoGrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_grupo_id");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razao_social");

                    b.Property<int>("RegimeApuracao")
                        .HasColumnType("integer")
                        .HasColumnName("regime_apuracao");

                    b.Property<int>("RegimeTributario")
                        .HasColumnType("integer")
                        .HasColumnName("regime_tributario");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenMercadoPagoPix")
                        .HasColumnType("text")
                        .HasColumnName("token_mercado_pago_pix");

                    b.Property<Guid?>("TributarioGrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tributario_grupo_id");

                    b.HasKey("Id")
                        .HasName("p_k_empresas");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__empresa_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__empresa_tenant_id");

                    b.ToTable("empresas", "plataforma");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<string>("Complemento")
                        .HasColumnType("text")
                        .HasColumnName("complemento");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("logradouro");

                    b.Property<long>("MunicipioId")
                        .HasColumnType("bigint")
                        .HasColumnName("municipio_id");

                    b.Property<string>("Numero")
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<long>("PaisId")
                        .HasColumnType("bigint")
                        .HasColumnName("pais_id");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<string>("Referencia")
                        .HasColumnType("text")
                        .HasColumnName("referencia");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TipoEndereco")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_endereco");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uf");

                    b.HasKey("Id")
                        .HasName("p_k_enderecos_pessoas");

                    b.HasIndex("PessoaId")
                        .HasDatabaseName("i_x_enderecos_pessoas_pessoa_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__endereco_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__endereco_tenant_id");

                    b.ToTable("enderecos_pessoas", "plataforma");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.Fatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pagamento");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vencimento");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("p_k_faturas");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__fatura_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__fatura_tenant_id");

                    b.ToTable("faturas", "plataforma");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.ModuloPlano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("NomeModulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_modulo");

                    b.Property<Guid>("PlanoId")
                        .HasColumnType("uuid")
                        .HasColumnName("plano_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("p_k_modulos_plano");

                    b.HasIndex("PlanoId")
                        .HasDatabaseName("i_x_modulos_plano_plano_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__modulo_plano_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__modulo_plano_tenant_id");

                    b.ToTable("modulos_plano", "plataforma");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.PerfilUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cargo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("departamento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<decimal>("LimiteDesconto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("limite_desconto");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_perfis_usuarios");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__perfil_usuario_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__perfil_usuario_tenant_id");

                    b.ToTable("perfis_usuarios", "plataforma");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgenciaContaBancaria")
                        .HasColumnType("text")
                        .HasColumnName("agencia_conta_bancaria");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<string>("ChavePix")
                        .HasColumnType("text")
                        .HasColumnName("chave_pix");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<bool>("EhCliente")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_cliente");

                    b.Property<bool>("EhFornecedor")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_fornecedor");

                    b.Property<bool>("EhFuncionario")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_funcionario");

                    b.Property<bool>("EhInativo")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_inativo");

                    b.Property<bool>("EhMotorista")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_motorista");

                    b.Property<bool>("EhPrestadorServico")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_prestador_servico");

                    b.Property<bool>("EhProdutorRural")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_produtor_rural");

                    b.Property<bool>("EhTransportadora")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_transportadora");

                    b.Property<long?>("InscricaoSuframa")
                        .HasColumnType("bigint")
                        .HasColumnName("inscricao_suframa");

                    b.Property<string>("NumeroContaBancaria")
                        .HasColumnType("text")
                        .HasColumnName("numero_conta_bancaria");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<Guid?>("PessoaGrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_grupo_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TipoIndicadorIe")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_indicador_ie");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_pessoa");

                    b.Property<int?>("TipoPix")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_pix");

                    b.Property<string>("TitularContaBancaria")
                        .HasColumnType("text")
                        .HasColumnName("titular_conta_bancaria");

                    b.HasKey("Id")
                        .HasName("p_k_pessoas");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__pessoa_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__pessoa_tenant_id");

                    b.ToTable("pessoas", "plataforma");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.PessoaCliente", b =>
                {
                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<bool>("EhConsumidorFinal")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_consumidor_final");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TipoContribuinte")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_contribuinte");

                    b.HasKey("PessoaId")
                        .HasName("p_k_pessoas_clientes");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__pessoa_cliente_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__pessoa_cliente_tenant_id");

                    b.ToTable("pessoas_clientes", "plataforma");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.PessoaContato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<bool>("EhPrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_principal");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("NumeroTelefone")
                        .HasColumnType("text")
                        .HasColumnName("numero_telefone");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TipoContatoEmail")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_contato_email");

                    b.Property<int>("TipoContatoTelefonico")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_contato_telefonico");

                    b.HasKey("Id")
                        .HasName("p_k_pessoas_contatos");

                    b.HasIndex("PessoaId")
                        .HasDatabaseName("i_x_pessoas_contatos_pessoa_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__pessoa_contato_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__pessoa_contato_tenant_id");

                    b.ToTable("pessoas_contatos", "plataforma");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.PessoaEstrangeiro", b =>
                {
                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("IdentificacaoEstrangeiro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identificacao_estrangeiro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("PessoaId")
                        .HasName("p_k_pessoas_estrangeiros");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__pessoa_estrangeiro_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__pessoa_estrangeiro_tenant_id");

                    b.ToTable("pessoas_estrangeiros", "plataforma");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.PessoaFisica", b =>
                {
                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_nascimento");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("RgNumero")
                        .HasColumnType("text")
                        .HasColumnName("rg_numero");

                    b.Property<string>("RgOrgaoEmissor")
                        .HasColumnType("text")
                        .HasColumnName("rg_orgao_emissor");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("text")
                        .HasColumnName("sobrenome");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TipoGenero")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_genero");

                    b.HasKey("PessoaId")
                        .HasName("p_k_pessoas_fisicas");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__pessoa_fisica_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__pessoa_fisica_tenant_id");

                    b.ToTable("pessoas_fisicas", "plataforma");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.PessoaFuncionario", b =>
                {
                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TipoCargo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_cargo");

                    b.Property<decimal>("ValorPercentualComissao")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_percentual_comissao");

                    b.HasKey("PessoaId")
                        .HasName("p_k_pessoas_funcionarios");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__pessoa_funcionario_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__pessoa_funcionario_tenant_id");

                    b.ToTable("pessoas_funcionarios", "plataforma");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.PessoaGrupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("p_k_pessoa_grupos");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__pessoa_grupo_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__pessoa_grupo_tenant_id");

                    b.ToTable("pessoa_grupos", "plataforma");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.PessoaJuridica", b =>
                {
                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<string>("Cnae")
                        .HasColumnType("text")
                        .HasColumnName("cnae");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("text")
                        .HasColumnName("inscricao_estadual");

                    b.Property<string>("InscricaoMunicipal")
                        .HasColumnType("text")
                        .HasColumnName("inscricao_municipal");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("text")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razao_social");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("PessoaId")
                        .HasName("p_k_pessoas_juridicas");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__pessoa_juridica_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__pessoa_juridica_tenant_id");

                    b.ToTable("pessoas_juridicas", "plataforma");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.PessoaMotorista", b =>
                {
                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DataEmissaoCnh")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_emissao_cnh");

                    b.Property<DateTime?>("DataVencimentoCnh")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vencimento_cnh");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Rntrc")
                        .HasColumnType("text")
                        .HasColumnName("rntrc");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TipoCategoriaCnh")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_categoria_cnh");

                    b.Property<int>("TipoVinculoMotorista")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_vinculo_motorista");

                    b.HasKey("PessoaId")
                        .HasName("p_k_pessoas_motoristas");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__pessoa_motorista_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__pessoa_motorista_tenant_id");

                    b.ToTable("pessoas_motoristas", "plataforma");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.PessoaPrestadorServico", b =>
                {
                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<string>("Cei")
                        .HasColumnType("text")
                        .HasColumnName("cei");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("PessoaId")
                        .HasName("p_k_pessoas_prestadores_servico");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__pessoa_prestador_servico_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__pessoa_prestador_servico_tenant_id");

                    b.ToTable("pessoas_prestadores_servico", "plataforma");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.PessoaTransportadora", b =>
                {
                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<string>("Ciot")
                        .HasColumnType("text")
                        .HasColumnName("ciot");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Rntrc")
                        .HasColumnType("text")
                        .HasColumnName("rntrc");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("PessoaId")
                        .HasName("p_k_pessoas_transportadoras");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__pessoa_transportadora_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__pessoa_transportadora_tenant_id");

                    b.ToTable("pessoas_transportadoras", "plataforma");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.PessoaVeiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<long>("PaisId")
                        .HasColumnType("bigint")
                        .HasColumnName("pais_id");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("placa");

                    b.Property<string>("Rntrc")
                        .HasColumnType("text")
                        .HasColumnName("rntrc");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TipoVeiculo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_veiculo");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uf");

                    b.HasKey("Id")
                        .HasName("p_k_pessoas_veiculos");

                    b.HasIndex("PessoaId")
                        .HasDatabaseName("i_x_pessoas_veiculos_pessoa_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__pessoa_veiculo_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__pessoa_veiculo_tenant_id");

                    b.ToTable("pessoas_veiculos", "plataforma");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.Plano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("preco");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("p_k_planos");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__plano_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__plano_tenant_id");

                    b.ToTable("planos", "plataforma");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.UsuarioPermissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("acao");

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasColumnType("text")
                        .HasColumnName("alterado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<Guid>("PerfilUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_usuario_id");

                    b.Property<bool>("Permitido")
                        .HasColumnType("boolean")
                        .HasColumnName("permitido");

                    b.Property<string>("Recurso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recurso");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_id");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sync_version");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("p_k_usuarios_permissoes");

                    b.HasIndex("PerfilUsuarioId")
                        .HasDatabaseName("i_x_usuarios_permissoes_perfil_usuario_id");

                    b.HasIndex("SyncId")
                        .IsUnique()
                        .HasDatabaseName("ix__usuario_permissao_sync_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix__usuario_permissao_tenant_id");

                    b.ToTable("usuarios_permissoes", "plataforma");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.ContratoItem", b =>
                {
                    b.HasOne("Epros.Modules.GestaoClientes.Domain.Entities.Contrato", null)
                        .WithMany("Itens")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_contrato_itens_contratos_contrato_id");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.Empresa", b =>
                {
                    b.OwnsOne("Epros.Modules.GestaoClientes.Domain.ValueObjects.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("bairro");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("cep");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("cidade");

                            b1.Property<string>("Complemento")
                                .HasColumnType("text")
                                .HasColumnName("complemento");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("estado");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("logradouro");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("numero");

                            b1.HasKey("EmpresaId")
                                .HasName("p_k_empresas");

                            b1.ToTable("empresas", "plataforma");

                            b1.WithOwner()
                                .HasForeignKey("EmpresaId")
                                .HasConstraintName("f_k_empresas_empresas_id");
                        });

                    b.Navigation("Endereco")
                        .IsRequired();
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.Endereco", b =>
                {
                    b.HasOne("Epros.Modules.GestaoClientes.Domain.Entities.Pessoa", null)
                        .WithMany("Enderecos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_enderecos_pessoas__pessoas_pessoa_id");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.ModuloPlano", b =>
                {
                    b.HasOne("Epros.Modules.GestaoClientes.Domain.Entities.Plano", null)
                        .WithMany("Modulos")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_modulos_plano__planos_plano_id");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.PessoaCliente", b =>
                {
                    b.HasOne("Epros.Modules.GestaoClientes.Domain.Entities.Pessoa", null)
                        .WithOne("PessoaCliente")
                        .HasForeignKey("Epros.Modules.GestaoClientes.Domain.Entities.PessoaCliente", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_pessoas_clientes_pessoas_pessoa_id");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.PessoaContato", b =>
                {
                    b.HasOne("Epros.Modules.GestaoClientes.Domain.Entities.Pessoa", null)
                        .WithMany("Contatos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_pessoas_contatos_pessoas_pessoa_id");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.PessoaEstrangeiro", b =>
                {
                    b.HasOne("Epros.Modules.GestaoClientes.Domain.Entities.Pessoa", null)
                        .WithOne("PessoaEstrangeiro")
                        .HasForeignKey("Epros.Modules.GestaoClientes.Domain.Entities.PessoaEstrangeiro", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_pessoas_estrangeiros_pessoas_pessoa_id");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.PessoaFisica", b =>
                {
                    b.HasOne("Epros.Modules.GestaoClientes.Domain.Entities.Pessoa", null)
                        .WithOne("PessoaFisica")
                        .HasForeignKey("Epros.Modules.GestaoClientes.Domain.Entities.PessoaFisica", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_pessoas_fisicas_pessoas_pessoa_id");

                    b.OwnsOne("Epros.Modules.GestaoClientes.Domain.ValueObjects.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("PessoaFisicaPessoaId")
                                .HasColumnType("uuid")
                                .HasColumnName("pessoa_id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("valor");

                            b1.HasKey("PessoaFisicaPessoaId")
                                .HasName("p_k_pessoas_fisicas");

                            b1.ToTable("pessoas_fisicas", "plataforma");

                            b1.WithOwner()
                                .HasForeignKey("PessoaFisicaPessoaId")
                                .HasConstraintName("f_k_pessoas_fisicas_pessoas_fisicas_pessoa_id");
                        });

                    b.Navigation("Cpf")
                        .IsRequired();
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.PessoaFuncionario", b =>
                {
                    b.HasOne("Epros.Modules.GestaoClientes.Domain.Entities.Pessoa", null)
                        .WithOne("PessoaFuncionario")
                        .HasForeignKey("Epros.Modules.GestaoClientes.Domain.Entities.PessoaFuncionario", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_pessoas_funcionarios_pessoas_pessoa_id");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.PessoaJuridica", b =>
                {
                    b.HasOne("Epros.Modules.GestaoClientes.Domain.Entities.Pessoa", null)
                        .WithOne("PessoaJuridica")
                        .HasForeignKey("Epros.Modules.GestaoClientes.Domain.Entities.PessoaJuridica", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_pessoas_juridicas_pessoas_pessoa_id");

                    b.OwnsOne("Epros.Modules.GestaoClientes.Domain.ValueObjects.Cnpj", "Cnpj", b1 =>
                        {
                            b1.Property<Guid>("PessoaJuridicaPessoaId")
                                .HasColumnType("uuid")
                                .HasColumnName("pessoa_id");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("valor");

                            b1.HasKey("PessoaJuridicaPessoaId")
                                .HasName("p_k_pessoas_juridicas");

                            b1.ToTable("pessoas_juridicas", "plataforma");

                            b1.WithOwner()
                                .HasForeignKey("PessoaJuridicaPessoaId")
                                .HasConstraintName("f_k_pessoas_juridicas_pessoas_juridicas_pessoa_id");
                        });

                    b.Navigation("Cnpj")
                        .IsRequired();
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.PessoaMotorista", b =>
                {
                    b.HasOne("Epros.Modules.GestaoClientes.Domain.Entities.Pessoa", null)
                        .WithOne("PessoaMotorista")
                        .HasForeignKey("Epros.Modules.GestaoClientes.Domain.Entities.PessoaMotorista", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_pessoas_motoristas_pessoas_pessoa_id");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.PessoaPrestadorServico", b =>
                {
                    b.HasOne("Epros.Modules.GestaoClientes.Domain.Entities.Pessoa", null)
                        .WithOne("PessoaPrestadorServico")
                        .HasForeignKey("Epros.Modules.GestaoClientes.Domain.Entities.PessoaPrestadorServico", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_pessoas_prestadores_servico_pessoas_pessoa_id");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.PessoaTransportadora", b =>
                {
                    b.HasOne("Epros.Modules.GestaoClientes.Domain.Entities.Pessoa", null)
                        .WithOne("PessoaTransportadora")
                        .HasForeignKey("Epros.Modules.GestaoClientes.Domain.Entities.PessoaTransportadora", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_pessoas_transportadoras_pessoas_pessoa_id");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.PessoaVeiculo", b =>
                {
                    b.HasOne("Epros.Modules.GestaoClientes.Domain.Entities.Pessoa", null)
                        .WithMany("Veiculos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_pessoas_veiculos_pessoas_pessoa_id");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.UsuarioPermissao", b =>
                {
                    b.HasOne("Epros.Modules.GestaoClientes.Domain.Entities.PerfilUsuario", null)
                        .WithMany("Permissoes")
                        .HasForeignKey("PerfilUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_usuarios_permissoes_perfis_usuarios_perfil_usuario_id");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.Contrato", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.PerfilUsuario", b =>
                {
                    b.Navigation("Permissoes");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.Pessoa", b =>
                {
                    b.Navigation("Contatos");

                    b.Navigation("Enderecos");

                    b.Navigation("PessoaCliente");

                    b.Navigation("PessoaEstrangeiro");

                    b.Navigation("PessoaFisica");

                    b.Navigation("PessoaFuncionario");

                    b.Navigation("PessoaJuridica");

                    b.Navigation("PessoaMotorista");

                    b.Navigation("PessoaPrestadorServico");

                    b.Navigation("PessoaTransportadora");

                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("Epros.Modules.GestaoClientes.Domain.Entities.Plano", b =>
                {
                    b.Navigation("Modulos");
                });
#pragma warning restore 612, 618
        }
    }
}
