<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.26" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\Epros.Infrastructure\Epros.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Epros.Modules.GestaoClientes\Epros.Modules.GestaoClientes.csproj" />
    <ProjectReference Include="..\..\Modules\Epros.Modules.Estoque\Epros.Modules.Estoque.csproj" />
    <ProjectReference Include="..\..\Modules\Epros.Modules.Fiscal\Epros.Modules.Fiscal.csproj" />
    <ProjectReference Include="..\..\Modules\Epros.Modules.Financeiro\Epros.Modules.Financeiro.csproj" />
    <ProjectReference Include="..\..\Modules\Epros.Modules.Vendas\Epros.Modules.Vendas.csproj" />
    <ProjectReference Include="..\..\Modules\Epros.Modules.Aplicativo\Epros.Modules.Aplicativo.csproj" />
    <ProjectReference Include="..\..\Modules\Epros.Modules.Qualidade\Epros.Modules.Qualidade.csproj" />
    <ProjectReference Include="..\..\Modules\Epros.Modules.Producao\Epros.Modules.Producao.csproj" />
    <ProjectReference Include="..\..\Modules\Epros.Modules.RH\Epros.Modules.RH.csproj" />
    <ProjectReference Include="..\..\Modules\Epros.Modules.Projetos\Epros.Modules.Projetos.csproj" />
    <ProjectReference Include="..\..\Modules\Epros.Modules.Manutencao\Epros.Modules.Manutencao.csproj" />
    <ProjectReference Include="..\..\Modules\Epros.Modules.GRC\Epros.Modules.GRC.csproj" />
    <ProjectReference Include="..\..\Modules\Epros.Modules.ESG\Epros.Modules.ESG.csproj" />
    <ProjectReference Include="..\..\Modules\Epros.Modules.DMS\Epros.Modules.DMS.csproj" />
    <ProjectReference Include="..\..\Modules\Epros.Modules.Imobiliaria\Epros.Modules.Imobiliaria.csproj" />
  </ItemGroup>

</Project>
